version: 0.2

phases:

  pre_build:
    command:
      - echo "building resumes..."

  # generate all the resume versions
  build:
    commands:
      # from markdown 
      # - pandoc ./src/resumes/resume.md -f markdown -t html -s -o ./resume.html
      # - pandoc ./src/resumes/resume.md -f markdown -t docx -o ./resume.docx

      # from latex
      - pandoc ./src/resumes/test.latex -f latex -o ./test.pdf
      # - pandoc ./resume.latex -f latex -o ./test.html
      # - pandoc ./resume.latex -f latex -o ./test.docx
      # - pandoc ./resume.latex -f latex -o ./test.md

  post_build:
    commands:
      - aws s3 sync ./ s3://com.cuffney.resume  --delete
