version: 0.2

phases:

  pre_build:
    command:
      - echo "building resumes..."

  # generate all the resume versions
  build:
    commands:
      # html 
      # TODO: (checkout number 3 at the follow link: https://pandoc.org/demos.html)
      - pandoc ./src/resumes/resume.md -f markdown -t html -s -o ./public/resume.html
      # docx
      - pandoc ./src/resumes/resume.md -f markdown -t docx -o ./public/resume.docx
      # rtf
      - pandoc ./src/resumes/resume.md -f markdown -t docx -o ./public/resume.rtf
      # pdf (not currently working)
      # - pandoc ./src/resumes/resume.md -f markdown -t pdf -o ./public/resume.pdf
      # tex (not currently working)
      # - pandoc ./src/resumes/resume.md -f markdown -t tex -o ./public/resume.tex

      # TODO: convert .tex --> .md
      # - pandoc ./src/resumes/resume.tex -f tex -t markdown -o ./public/resume.md
      # - pandoc ./resume.tex -f tex -t markdown -o ./resume.md

      # this worked
      # pandoc ./resume.latex -f latex -o ./test.pdf

      - aws s3 sync ./ s3://com.cuffney.resume  --delete
