version: 0.2

phases:

  pre_build:
    command:
      - echo "building resume..."

  build:
    commands:

      # from markdown --> *
      - pandoc ./src/resume.md -f markdown -o ./public/resume.pdf
      - pandoc ./src/resume.md -f markdown -o ./public/resume.docx
      - cp ./src/resume.md ./public/resume.md

  post_build:
    commands:
      - aws s3 sync ./public s3://resume.cuffney.com  --delete
