version: 0.2

env:
  variables:
    CF_DISTRIBUTON_ID: E1N7J4N30PZBSO

phases:

  pre_build:
    command:
      - echo "building resume..."

  build:
    commands:
      # from markdown --> *
      # - pandoc ./resume.md -f markdown -o ./public/resume.html
      # - pandoc -s -c ./styles.css ./resume.md  -o ./public/index.html
      - pandoc -s --metadata title="Joseph Cuffney's Resume"  -c ./styles.css -H ./header.html ./resume.md  -o ./public/index.html
      - cp ./resume.md ./public/resume.md
      - cp ./styles.css ./public/styles.css

  post_build:
    commands:
      - aws s3 sync ./public s3://resume.cuffney.com  --delete
      - aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTON_ID} --paths /*
