version: 0.2

# env:
#   variables:
#     CF_DISTRIBUTON_ID:
#     S3_BUCKET_NAME: 

phases:

  pre_build:
    command:
      - echo "building resumes..."

  # generate all the resume versions
  # TODO: make this rescursive within `src/resumes`
  build:
    commands:
      # html 
      # TODO: (checkout number 3 at the follow link: https://pandoc.org/demos.html)
      - pandoc ./src/resumes/resume.md -f markdown -t html -s -o ./public/resume.html
      # docx
      - pandoc ./src/resumes/resume.md -f markdown -t docx -o ./public/resume.docx
      # rtf
      - pandoc ./src/resumes/resume.md -f markdown -t docx -o ./public/resume.rtf
      # pdf (not currently working)
      # - pandoc ./src/resumes/resume.md -f markdown -t pdf -o ./public/resume.pdf
      # tex (not currently working)
      # - pandoc ./src/resumes/resume.md -f markdown -t tex -o ./public/resume.tex

  # upload all the build resume's to s3
  # post_build:
  #   commands:
  #     - aws s3 sync ./public s3://resume.cuffney.com --delete

  # invalidate cloudfront
  # finally:
  #   commands:
  #     - aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTON_ID} --paths /*