version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.0
  jq: circleci/jq@2.0.2

jobs:

  infra: 
    executor: node/default
    steps:
      - checkout
      - run: npx serverless deploy --stage ${CIRCLE_BRANCH}

  deploy:
    executor: node/default
    steps:
      - checkout
      - aws-cli/setup
      - jq/install
      - run: |
          DISTRIBUTION_ID=$(aws ssm get-parameter --name /onset/${CIRCLE_BRANCH}/website/distribution/id | jq -r '.Parameter.Value')
          SOURCE_BUCKET_NAME=$(aws ssm get-parameter --name /onset/${CIRCLE_BRANCH}/website/source-bucket/name | jq -r '.Parameter.Value')
          aws s3 sync ./build s3://$SOURCE_BUCKET_NAME --delete
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

workflows:
  version: 2
  primary:
    jobs:
      - infra:
          context: cuffney
          filters:
            branches:
              only:
                - master
      - deploy:
          context: cuffney 
          requires:
            - infra
          filters:
            branches:
              only:
                - master
