version: 2
defaults: &defaults
  docker: 
    - image: jcuffney/node-ci-image:1.0.26
  working_directory: ~/rep

jobs:

  validate_cloudformation: 
    <<: *defaults
    steps:
      - checkout

      - run:
          name: validate cloudformation
          command: |
            aws cloudformation validate-template \
              --template-body file://infra/template.json

  deploy_infra:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: deploy infrastructure
          command: |
            aws cloudformation deploy \
              --stack-name resume-cuffney-com \
              --template-file ./infra/template.json \
              --region us-east-1 \
              --capabilities CAPABILITY_IAM \
              --no-fail-on-empty-changeset \
              --parameter-overrides \
                DomainName=resume.cuffney.com \
                HostedZoneId=Z17UESAG3QE29Y \
                AcmCertificateArn=arn:aws:acm:us-east-1:255964265911:certificate/3a6c2c22-cb43-4c9b-9462-cf261b498eea

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-build-{{ checksum "package.json" }}

      - run:
          name: sync build to s3
          command: |
            aws s3 sync ./build s3://resume.cuffney.com --delete

      - run:
          name: Create CloudFront Invalidation
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - validate_cloudformation
      - deploy_infra:
          requires: 
            - validate_cloudformation
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - deploy_infra
          filters:
            branches:
              only: master
